# devil
(ꔸ࿆͋͋͋͋͋͋̑ꔸ࿆͋͋͋͋͋̑ꔸ࿆͋͋͋͋̑ꔸ࿆͋͋͋̑ꔸ࿆͋͋̑ꔸ࿆͋̑ꔸ࿆̑ꔸ࿆͋͋͋͋͋͋̑ꔸ࿆͋͋͋͋͋̑ꔸ࿆͋͋͋͋̑ꔸ࿆͋͋͋̑ꔸ࿆͋͋̑ꔸ࿆͋̑ꔸ࿆̑ꔰ࿆࿆̈́̑̈́̑ꔸ࿆̑ꔸ࿆͋̑ꔸ࿆͋͋̑ꔸ࿆͋͋͋̑ꔸ࿆͋͋͋͋̑ꔸ࿆͋͋͋͋͋̑ꔸ࿆͋͋͋͋͋͋̑ꔸ࿆̑ꔸ࿆͋̑ꔸ࿆͋͋̑ꔸ࿆͋͋͋̑ꔸ࿆͋͋͋͋̑ꔸ࿆͋͋͋͋͋̑ꔸ࿆͋͋͋͋͋͋̑)
@@ -9,4 +9,3 @@ community_bridge: botol-baba-tool

liberapay: botolbaba

issuehunt: botolbaba

otechie: botolbaba

lfx_crowdfunding: cloud-foundry
